spring.application.name=touristsafety
spring.datasource.url=jdbc:mysql://localhost:3306/tourist_safety_db
spring.datasource.username=root
spring.datasource.password=Kaushtubhi@46
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080