
spring.application.name=tourism
spring.datasource.url=jdbc:mysql://localhost:3307/sos_db
spring.datasource.username=root
spring.datasource.password=181503

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080


